server:
  port: 8888
datasource:
  driverName: mysql
  host: 47.100.108.193
  port: 3306
  database: clf
  username: root
  password: czx987852
  charset: utf8
redis:
  addr: 47.100.108.193:6379
  password: czx987852
  db: 0
smtp:
  port: 465
  host: smtp.163.com
  email: clf2863768433@163.com
  password: qazwsxedc2580
iotsource:
  accessKey: LTAI4FiwZ4r1BZ5cz1kyhuFc
  accessSecret: drErA9WaHJz2S5D728w0HvyvYhBg7d
  regionId: cn-shanghai
