server:
  port: 8080
datasource:
  host: 47.100.108.193
  port: 3306
  database: clf
  username: root
  password: czx987852
  charset: utf8mb4
redis:
  addr: 47.100.108.193:6379
  password: czx987852
  db: 0
smtp:
  port: 465
  host: smtp.163.com
  email: clf2863768433@163.com
  password: qazwsxedc2580
mongodb:
  host: 47.100.108.193
  port: 27017
  username: admin
  password: czx987852
  logdb: clf
aliyuniot:
  accessKey: LTAI4FiwZ4r1BZ5cz1kyhuFc
  accessSecret: drErA9WaHJz2S5D728w0HvyvYhBg7d
  regionId: cn-shanghai
  uid: 1734109065164743
  region: cn-shanghai
  consumerGroupId: DEFAULT_GROUP
  clientId: 47.100.192.108


